<br><br>
<section id="customer-partner">
    <div class="container-fluid">
        <div class="row justify-content-center mb-3 mb-lg-5">
            <div class="col-12 text-center mb-3 mb-lg-5">
                <h2>Telah Dipercaya oleh 45.000+ Pelanggan Aktif</h2>
            </div>
            <div class="col-12 text-center">
                <div class="image-list">
                    <img data-lazyloaded="1" data-placeholder-resp="200pxx85px" src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Pelanggan/Cimory.webp" loading="lazy" data-src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Pelanggan/Cimory.webp" alt="Cimory" width="200px" height="85px" data-ll-status="loaded" class="entered litespeed-loaded"><noscript><img loading="lazy" src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Pelanggan/Cimory.webp" alt="Cimory" width="200px" height="85px" /></noscript>
                    <img data-lazyloaded="1" data-placeholder-resp="200pxx85px" src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Pelanggan/Forisa.webp" loading="lazy" data-src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Pelanggan/Forisa.webp" alt="Forisa" width="200px" height="85px" data-ll-status="loaded" class="entered litespeed-loaded"><noscript><img loading="lazy" src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Pelanggan/Forisa.webp" alt="Forisa" width="200px" height="85px" /></noscript>
                    <img data-lazyloaded="1" data-placeholder-resp="200pxx85px" src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Pelanggan/Elsheskin.webp" loading="lazy" data-src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Pelanggan/Elsheskin.webp" alt="Elsheskin" width="200px" height="85px" data-ll-status="loaded" class="entered litespeed-loaded"><noscript><img loading="lazy" src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Pelanggan/Elsheskin.webp" alt="Elsheskin" width="200px" height="85px" /></noscript>
                    <img data-lazyloaded="1" data-placeholder-resp="200pxx85px" src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Pelanggan/Icon.webp" loading="lazy" data-src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Pelanggan/Icon.webp" alt="Icon +" width="200px" height="85px" data-ll-status="loaded" class="entered litespeed-loaded"><noscript><img loading="lazy" src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Pelanggan/Icon.webp" alt="Icon +" width="200px" height="85px" /></noscript>
                    <img data-lazyloaded="1" data-placeholder-resp="200pxx85px" src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Pelanggan/Horison.webp" loading="lazy" data-src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Pelanggan/Horison.webp" alt="Horison" width="200px" height="85px" data-ll-status="loaded" class="entered litespeed-loaded"><noscript><img loading="lazy" src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Pelanggan/Horison.webp" alt="Horison" width="200px" height="85px" /></noscript>
                    <img data-lazyloaded="1" data-placeholder-resp="200pxx85px" src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Pelanggan/MD.webp" loading="lazy" data-src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Pelanggan/MD.webp" alt="MD Pictures" width="200px" height="85px" data-ll-status="loaded" class="entered litespeed-loaded"><noscript><img loading="lazy" src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Pelanggan/MD.webp" alt="MD Pictures" width="200px" height="85px" /></noscript>
                </div>
                <a href="#" class="text-qw-primary fw-bold text-decoration-none">Dan Masih Banyak yang Lainnya
                    <img data-lazyloaded="1" data-placeholder-resp="20pxx20px" src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/Right.webp" loading="lazy" class="ms-3 entered litespeed-loaded" data-src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/Right.webp" alt="Right.webp" width="20px" height="20px" data-ll-status="loaded"><noscript><img loading="lazy" class="ms-3" src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/Right.webp" alt="Right.webp" width="20px" height="20px" /></noscript>
                </a>
            </div>
        </div>
        <div class="row justify-content-center pt-3 pt-lg-5">
            <div class="col-12 text-center mb-3 mb-lg-4">
                <h2>Partner Kami</h2>
            </div>
            <div class="col-12 text-center">
                <div class="image-list">
                    <img data-lazyloaded="1" data-placeholder-resp="200pxx85px" src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Partner/Google.webp" loading="lazy" data-src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Partner/Google.webp" alt="Google Cloud" width="200px" height="85px" data-ll-status="loaded" class="entered litespeed-loaded"><noscript><img loading="lazy" src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Partner/Google.webp" alt="Google Cloud" width="200px" height="85px" /></noscript>
                    <img data-lazyloaded="1" data-placeholder-resp="200pxx85px" src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Partner/Cpanel.webp" loading="lazy" data-src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Partner/Cpanel.webp" alt="Cpanel" width="200px" height="85px" data-ll-status="loaded" class="entered litespeed-loaded"><noscript><img loading="lazy" src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Partner/Cpanel.webp" alt="Cpanel" width="200px" height="85px" /></noscript>
                    <img data-lazyloaded="1" data-placeholder-resp="200pxx85px" src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Partner/Idea.webp" loading="lazy" data-src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Partner/Idea.webp" alt="Idea" width="200px" height="85px" data-ll-status="loaded" class="entered litespeed-loaded"><noscript><img loading="lazy" src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Partner/Idea.webp" alt="Idea" width="200px" height="85px" /></noscript>
                    <img data-lazyloaded="1" data-placeholder-resp="200pxx85px" src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Partner/Archi.webp" loading="lazy" data-src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Partner/Archi.webp" alt="Archi" width="200px" height="85px" data-ll-status="loaded" class="entered litespeed-loaded"><noscript><img loading="lazy" src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Partner/Archi.webp" alt="Archi" width="200px" height="85px" /></noscript>
                    <img data-lazyloaded="1" data-placeholder-resp="200pxx85px" src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Partner/dotid.webp" loading="lazy" data-src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Partner/dotid.webp" alt="dotid" width="200px" height="85px" data-ll-status="loaded" class="entered litespeed-loaded"><noscript><img loading="lazy" src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/partner-customer/Partner/dotid.webp" alt="dotid" width="200px" height="85px" /></noscript>
                </div>
                <a href="#" class="text-qw-primary fw-bold text-decoration-none">Lihat Semua Partner
                    <img data-lazyloaded="1" data-placeholder-resp="20pxx20px" src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/Right.webp" loading="lazy" class="ms-3 entered litespeed-loaded" data-src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/Right.webp" alt="Right.webp" width="20px" height="20px" data-ll-status="loaded"><noscript><img loading="lazy" class="ms-3" src="https://qwords.com/v2/wp-content/themes/qwords/assets/images/icons/Right.webp" alt="Right.webp" width="20px" height="20px" /></noscript>
                </a>
            </div>
        </div>
    </div>
</section>